### ISSUE TITLE
If the automatic backup time occurs while the computer is off, the backup is not performed.

### ISSUE THREAD

**Issue by Terkyz** [GeovaneJefferson/timemachine#2]
It sounds dumb, but it would be useful an ability to choose several hours in which TimeMachine can try to make a backup and if this happened (computer is not turned on at the automatic backup time) on the first attempt, or also that it be done automatically when the computer boots after having missed the backup time

**Comment by GeovaneJefferson** [comment]
Nice idea! 
Will take a look about that.
Thanks for the feedback! :D

**Comment by GeovaneJefferson** [comment]
This features has been implemented!
Will be release on Time Machine v1.1.0
